elasticsearch:
  host: http://localhost:9200
  index: places

server:
  port: 2322

search:
  min_chars: 2
  fuzziness: AUTO
  max_results: 15

database:
  host: localhost
  port: 5432
  name: nominatim
  user: nominatim
  password: ""
