services:

  app:
    build: .
    command: ["./place-search", "serve"]
    ports:
      - "2322:2322"
    environment:
      - ES_HOST=http://elasticsearch:9200
      - ES_INDEX=places
      - SERVER_PORT=2322
      - SEARCH_MIN_CHARS=2
      - SEARCH_FUZZINESS=AUTO
      - SEARCH_MAX_RESULTS=15
    networks:
      - elastic-net

networks:
  elastic-net:
    external: true